name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Displays the Android dependencies of the project
        run: ./gradlew androidDependencies

      - name: Run Compile
        run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test --stacktrace

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*
          if-no-files-found: warn
          retention-days: 14


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Inspection
        run: ./gradlew lint

      - name: Show results on GitHub
        uses: yutailang0119/action-android-lint@v1
        with:
          xml_path: '**/build/reports/lint-results-*.xml'

      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error
          retention-days: 14

  ktlint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '17'

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - run: ./gradlew --init-script gradle/init.gradle.kts spotlessApply
        - uses: reviewdog/action-suggester@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            tool_name: spotless

        - name: Upload results Artifact
          uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: results
            path: |
              **/build/ktlint-report.xml
            if-no-files-found: error
            retention-days: 14
